// Trustle's words, in the order they're played: the first one on FIRST_DAY, then one more each day at
// midnight Eastern time (see scripts/trustle.js). After the last word the list starts over, shuffled.
//
// Add new words at the END. Words for days that haven't come yet can be changed or moved freely, but never
// touch today's or earlier ones: that changes today's word, and puzzles people already played.
//
// `word`: 3 to 9 letters, A to Z only. It doesn't need to be in the dictionary; every word here is always
//   accepted as a guess.
// `see` (optional): where the word comes from on the site, from PLACES below. It's linked after the game.

export const FIRST_DAY = '2026-09-29';

export const PLACES = {
  about: { href: '/pages/about.html', label: 'About Trusty' },
  comics: { href: '/pages/comics/datractorcrew/datractorcrew.html', label: 'Read Da Tractor Crew' },
  season2: { href: '/pages/comics/datractorcrew/season2.html', label: 'See the missing season' },
  games: { href: '/pages/games.html', label: 'See all the games' },
  flappy: { href: '/pages/games/flappy.html', label: 'Play Flappy Trusty' },
  snake: { href: '/pages/games/snake.html', label: 'Play Trusty Snake' },
  trustis: { href: '/pages/games/trustis.html', label: 'Play Trustis' },
  draw: { href: '/pages/games/draw.html', label: 'Play Draw Trusty' },
  casino: { href: '/pages/games/casino.html', label: 'Play Trusty Blackjack' },
  driving: { href: '/pages/games/driving.html', label: "Play Trusty's Traffic Crime Simulator" },
  cattle: { href: '/pages/games/crazycattle.html', label: "Play Trusty's Crazy Cattle 3D" },
  gta: { href: '/pages/games/gta.html', label: 'Play Grand Theft Trusty' },
  football: { href: '/pages/games/football.html', label: "Play Trusty NFL '94" },
  leaderboard: { href: '/pages/leaderboard.html', label: 'See the leaderboards' },
  tv: { href: '/pages/tv.html', label: 'Watch Trusty TV' },
  snn: { href: '/pages/tv.html#snn', label: 'Watch SNN' },
  spongebob: { href: '/pages/tv.html#spongebob', label: 'Watch channel 23' },
  gpt: { href: '/pages/trustyGPT.html', label: 'Chat with TrustyGPT' },
  weather: { href: '/pages/weather.html', label: 'Check Trusty Weather' },
  viewer: { href: '/pages/viewer.html', label: 'Spin 3D Trusty' },
  join: { href: '/pages/auth/register.html', label: 'Join the herd' },
};

export const WORDS = [
  { word: 'NEIGH' },
  { word: 'PENCIL', see: 'about' },
  { word: 'FLAPPY', see: 'flappy' },
  { word: 'TRACTOR', see: 'comics' },
  { word: 'SMILE', see: 'draw' },
  { word: 'BARN', see: 'weather' },
  { word: 'CASINO', see: 'casino' },
  { word: 'MARGIN', see: 'about' },
  { word: 'GALLOP', see: 'weather' },
  { word: 'KNIFE', see: 'tv' },
  { word: 'SEAHORSE', see: 'flappy' },
  { word: 'HAY' },
  { word: 'ALGEBRA' },
  { word: 'STALLION', see: 'snn' },
  { word: 'ORANGE', see: 'snake' },
  { word: 'EARS', see: 'draw' },
  { word: 'VIOLENT', see: 'gpt' },
  { word: 'UMBRELLA', see: 'weather' },
  { word: 'DOODLE' },
  { word: 'REWARD', see: 'season2' },
  { word: 'TWENTYONE', see: 'tv' },
  { word: 'SADDLE' },
  { word: 'TRUSTIS', see: 'trustis' },
  { word: 'GIRAFFE', see: 'tv' },
  { word: 'ERASER' },
  { word: 'HERD', see: 'join' },
  { word: 'TRUST', see: 'weather' },
  { word: 'PIGSKIN', see: 'football' },
  { word: 'CABASA', see: 'comics' },
  { word: 'WHINNY' },
  { word: 'HEAD', see: 'draw' },
  { word: 'SNAKE', see: 'snake' },
  { word: 'NOTEBOOK', see: 'about' },
  { word: 'CHANNEL', see: 'tv' },
  { word: 'OATS' },
  { word: 'BLACKJACK', see: 'casino' },
  { word: 'FLINT', see: 'comics' },
  { word: 'SUNSCREEN', see: 'weather' },
  { word: 'PONY' },
  { word: 'MATH', see: 'about' },
  { word: 'SCRIBBLE', see: 'draw' },
  { word: 'CRIMES', see: 'gta' },
  { word: 'STEED' },
  { word: 'GEMINI', see: 'gpt' },
  { word: 'PIPES', see: 'flappy' },
  { word: 'FOAL' },
  { word: 'JACKET', see: 'weather' },
  { word: 'NOGOOD', see: 'comics' },
  { word: 'CARTOON' },
  { word: 'TRUSTY', see: 'about' },
  { word: 'BOUNTY', see: 'tv' },
  { word: 'LASSO' },
  { word: 'INSURANCE', see: 'casino' },
  { word: 'STICK' },
  { word: 'DRIZZLE', see: 'weather' },
  { word: 'HOMEWORK' },
  { word: 'SPONGEBOB', see: 'spongebob' },
  { word: 'KICK', see: 'weather' },
  { word: 'SMITH', see: 'comics' },
  { word: 'MEMORIZE', see: 'draw' },
  { word: 'UNICORN' },
  { word: 'RIGGED', see: 'games' },
  { word: 'BACK', see: 'draw' },
  { word: 'FORECAST', see: 'weather' },
  { word: 'CRAYON' },
  { word: 'HORSE' },
  { word: 'ARCADE', see: 'games' },
  { word: 'TROJAN' },
  { word: 'DETENTION' },
  { word: 'JULIET', see: 'tv' },
  { word: 'APPLE' },
  { word: 'HORSEGUN', see: 'comics' },
  { word: 'CANTER' },
  { word: 'RADAR', see: 'weather' },
  { word: 'DEALER', see: 'casino' },
  { word: 'GRAPHITE' },
  { word: 'BOWL', see: 'football' },
  { word: 'MINION' },
  { word: 'SHADING', see: 'weather' },
  { word: 'COWBOY' },
  { word: 'STATIC', see: 'tv' },
  { word: 'EIGHTH', see: 'about' },
  { word: 'HOBBY' },
  { word: 'BUST', see: 'casino' },
  { word: 'SEASON', see: 'comics' },
  { word: 'THUNDER', see: 'weather' },
  { word: 'MANE' },
  { word: 'POLYGON', see: 'viewer' },
  { word: 'HELPFUL', see: 'gpt' },
  { word: 'CATTLE', see: 'cattle' },
  { word: 'SPIRAL' },
  { word: 'ZEBRA' },
  { word: 'WORLD', see: 'about' },
  { word: 'RECESS' },
  { word: 'TASTY', see: 'tv' },
  { word: 'HOOVES' },
  { word: 'BAILOUT', see: 'casino' },
  { word: 'SKETCH' },
  { word: 'FARM' },
  { word: 'CLOUDY', see: 'weather' },
  { word: 'TRUSTLE' },
  { word: 'JOCKEY' },
  { word: 'EPISODE', see: 'comics' },
  { word: 'FOIL', see: 'tv' },
  { word: 'HORSESHOE' },
  { word: 'VILLAIN' },
  { word: 'TRAFFIC', see: 'driving' },
  { word: 'INK', see: 'draw' },
  { word: 'RODEO' },
  { word: 'KNOB', see: 'tv' },
  { word: 'TEACHER', see: 'about' },
  { word: 'MULE' },
  { word: 'CONQUER' },
  { word: 'FLAP', see: 'flappy' },
  { word: 'SUNSET', see: 'weather' },
  { word: 'REINS' },
  { word: 'PORTRAIT' },
  { word: 'HOLD', see: 'trustis' },
  { word: 'WAGON' },
  { word: 'NEWS', see: 'snn' },
  { word: 'CENTAUR' },
  { word: 'RULER' },
  { word: 'CHIPS', see: 'casino' },
  { word: 'MISSING', see: 'season2' },
  { word: 'CARROT' },
  { word: 'GOLDEN', see: 'tv' },
  { word: 'NECK', see: 'draw' },
  { word: 'HENCHMAN' },
  { word: 'STABLE' },
  { word: 'BATTLE', see: 'tv' },
  { word: 'MARKER', see: 'about' },
  { word: 'BUCK' },
  { word: 'GEOMETRY' },
  { word: 'CLICKS', see: 'leaderboard' },
  { word: 'SNOW', see: 'weather' },
  { word: 'CREW', see: 'comics' },
  { word: 'MUSTANG' },
  { word: 'EMPIRE' },
  { word: 'PAPER' },
  { word: 'ARENA', see: 'cattle' },
  { word: 'COLT' },
  { word: 'TRAILER', see: 'tv' },
  { word: 'PASTURE' },
  { word: 'SCHEME' },
  { word: 'DRAW', see: 'draw' },
  { word: 'LOCKER' },
  { word: 'BRONCO' },
  { word: 'PERFECT', see: 'trustis' },
  { word: 'SUGAR' },
  { word: 'PODIUM', see: 'leaderboard' },
  { word: 'SHARPEN' },
  { word: 'OUTLAW' },
  { word: 'DERBY' },
  { word: 'ANTENNA', see: 'tv' },
  { word: 'LEGS', see: 'draw' },
  { word: 'CHAOS' },
  { word: 'SALOON' },
  { word: 'WHISKEY', see: 'tv' },
  { word: 'SHERIFF' },
  { word: 'EQUATION' },
  { word: 'PEGASUS', see: 'flappy' },
  { word: 'FENCE' },
  { word: 'GLUE' },
  { word: 'SUNNY', see: 'weather' },
  { word: 'MARE' },
  { word: 'OVERLORD' },
  { word: 'BURGER', see: 'snake' },
  { word: 'CAROUSEL' },
  { word: 'CAMPAIGN', see: 'tv' },
  { word: 'TROT' },
  { word: 'WESTERN' },
  { word: 'DESK' },
  { word: 'BLOCKS', see: 'trustis' },
  { word: 'KNIGHT' },
  { word: 'MAYHEM' },
  { word: 'HARVEST' },
  { word: 'SNORT' },
  { word: 'MARATHON', see: 'spongebob' },
  { word: 'FILLY' },
  { word: 'CRIMINAL', see: 'gpt' },
  { word: 'STIRRUP' },
  { word: 'LINES', see: 'draw' },
  { word: 'CHARIOT' },
  { word: 'PLOW' },
  { word: 'JOKE', see: 'gpt' },
  { word: 'RANCH' },
  { word: 'SPIN', see: 'viewer' },
  { word: 'FIGURE' },
  { word: 'HAYSTACK' },
  { word: 'BOOM', see: 'flappy' },
  { word: 'GROOM' },
  { word: 'PADDOCK' },
  { word: 'FORTNITE', see: 'tv' },
  { word: 'PANEL', see: 'comics' },
  { word: 'SHOE' },
  { word: 'TROUGH' },
  { word: 'FRACTION' },
  { word: 'HOWDY' },
  { word: 'PALOMINO' },
  { word: 'BRIDLE' },
  { word: 'LIVE', see: 'tv' },
  { word: 'BLINDERS' },
  { word: 'DIESEL' },
  { word: 'RIBBON' },
  { word: 'ROCKING' },
  { word: 'WANTED' },
  { word: 'TAIL', see: 'weather' },
  { word: 'BUGGY' },
  { word: 'FIELD' },
  { word: 'RACEHORSE' },
  { word: 'SCHOOL', see: 'about' },
  { word: 'SPURS' },
  { word: 'DONKEY' },
  { word: 'NIGHTMARE' },
  { word: 'CARRIAGE' },
  { word: 'HORSEPLAY' },
  { word: 'STAMPEDE' },
  { word: 'PONYTAIL' },
  { word: 'BACKPACK' },
  { word: 'MEADOW' },
  { word: 'CLOP' },
  { word: 'ARTIST' },
  { word: 'FARRIER' },
  { word: 'BELL' },
  { word: 'HORSEFLY' },
  { word: 'CROPS' },
  { word: 'DRAWING' },
  { word: 'GRAPH', see: 'trustis' },
  { word: 'STUDENT' },
  { word: 'SMUDGE' },
  { word: 'QUIZ' },
  { word: 'RIDER' },
];
