// Trustle's words, in the order they're played: the first one on FIRST_DAY, then one more each day at
// midnight Eastern time (see scripts/trustle.js). After the last word the list starts over, shuffled.
//
// Add new words at the END. Words for days that haven't come yet can be changed or moved freely, but never
// touch today's or earlier ones: that changes today's word, and puzzles people already played.
//
// `word`: 3 to 9 letters, A to Z only. It doesn't need to be in the dictionary; every word here is always
//   accepted as a guess.
// `hint`: Trusty's clue, shown if the player asks for one and again after the game. "___" marks a blank,
//   and the hint must not contain the word itself.
// `see` (optional): where the word comes from on the site, from PLACES below. It's linked after the game.

export const FIRST_DAY = '2026-09-29';

export const PLACES = {
  about: { href: '/pages/about.html', label: 'About Trusty' },
  comics: { href: '/pages/comics/datractorcrew/datractorcrew.html', label: 'Read Da Tractor Crew' },
  season2: { href: '/pages/comics/datractorcrew/season2.html', label: 'See the missing season' },
  games: { href: '/pages/games.html', label: 'See all the games' },
  flappy: { href: '/pages/games/flappy.html', label: 'Play Flappy Trusty' },
  snake: { href: '/pages/games/snake.html', label: 'Play Trusty Snake' },
  trustis: { href: '/pages/games/trustis.html', label: 'Play Trustis' },
  draw: { href: '/pages/games/draw.html', label: 'Play Draw Trusty' },
  casino: { href: '/pages/games/casino.html', label: 'Play Trusty Blackjack' },
  driving: { href: '/pages/games/driving.html', label: "Play Trusty's Traffic Crime Simulator" },
  cattle: { href: '/pages/games/crazycattle.html', label: "Play Trusty's Crazy Cattle 3D" },
  gta: { href: '/pages/games/gta.html', label: 'Play Grand Theft Trusty' },
  football: { href: '/pages/games/football.html', label: "Play Trusty NFL '94" },
  leaderboard: { href: '/pages/leaderboard.html', label: 'See the leaderboards' },
  tv: { href: '/pages/tv.html', label: 'Watch Trusty TV' },
  snn: { href: '/pages/tv.html#snn', label: 'Watch SNN' },
  spongebob: { href: '/pages/tv.html#spongebob', label: 'Watch channel 23' },
  gpt: { href: '/pages/trustyGPT.html', label: 'Chat with TrustyGPT' },
  weather: { href: '/pages/weather.html', label: 'Check Trusty Weather' },
  viewer: { href: '/pages/viewer.html', label: 'Spin 3D Trusty' },
  join: { href: '/pages/auth/register.html', label: 'Join the herd' },
};

export const WORDS = [
  { word: 'NEIGH', hint: 'What a horse says. I say it louder.' },
  { word: 'PENCIL', hint: 'What I was first drawn in.', see: 'about' },
  { word: 'FLAPPY', hint: '___ Trusty. Yo, that horse flying!', see: 'flappy' },
  { word: 'TRACTOR', hint: 'Da ___ Crew, the comic where it all started.', see: 'comics' },
  { word: 'SMILE', hint: 'Always on my face. Even when I’m plotting something.', see: 'draw' },
  { word: 'BARN', hint: 'Rain’s coming down. I’m staying in the ___.', see: 'weather' },
  { word: 'CASINO', hint: 'The horse ___. The games are probably rigged.', see: 'casino' },
  { word: 'MARGIN', hint: 'The edge of the page, where I was first drawn.', see: 'about' },
  { word: 'GALLOP', hint: 'What I do on clear days. Faster than a canter.', see: 'weather' },
  { word: 'KNIFE', hint: 'Trusty Finds His ___, a Trusty TV classic.', see: 'tv' },
  { word: 'SEAHORSE', hint: 'What I turn into at 20 points in Flappy Trusty.', see: 'flappy' },
  { word: 'HAY', hint: 'Breakfast, lunch and dinner. Dry, but it’s free.' },
  { word: 'ALGEBRA', hint: 'What that math class was supposed to be learning instead of drawing me.' },
  { word: 'STALLION', hint: 'The S in SNN, the ___ News Network.', see: 'snn' },
  { word: 'ORANGE', hint: 'My healthy snack in Trusty Snake.', see: 'snake' },
  { word: 'EARS', hint: 'I don’t have any. If you drew them on me, you went too far.', see: 'draw' },
  { word: 'VIOLENT', hint: 'TrustyGPT is helpful, but a little bit ___.', see: 'gpt' },
  { word: 'UMBRELLA', hint: 'Rain around 3? Bring one. Don’t say I didn’t warn you.', see: 'weather' },
  { word: 'DOODLE', hint: 'What the teacher called me. Rude.' },
  { word: 'REWARD', hint: 'Find Da Tractor Crew Season 2 and there’s a cash ___.', see: 'season2' },
  { word: 'TWENTYONE', hint: 'Blackjack’s magic number, and my channel on Trusty TV.', see: 'tv' },
  { word: 'SADDLE', hint: 'What you’d sit on if I let you ride me. I won’t.' },
  { word: 'TRUSTIS', hint: 'My version of Tetris. Fit the Trustys together!', see: 'trustis' },
  { word: 'GIRAFFE', hint: 'Among Us and ___, now airing on Trusty TV.', see: 'tv' },
  { word: 'ERASER', hint: 'My mortal enemy. Keep it away from the page.' },
  { word: 'HERD', hint: 'Join the ___! That’s what making an account here is.', see: 'join' },
  { word: 'TRUST', hint: '___ the horse. That’s how I sign off the weather.', see: 'weather' },
  { word: 'PIGSKIN', hint: 'Toss around the ol’ ___! (It’s a football.)', see: 'football' },
  { word: 'CABASA', hint: 'My birthplace: Mrs. ___’s 8th grade math class.', see: 'comics' },
  { word: 'WHINNY', hint: 'A horse’s laugh. Mine sounds evil.' },
  { word: 'HEAD', hint: 'Big and round. Draw it first.', see: 'draw' },
  { word: 'SNAKE', hint: 'Trusty ___: how long can you make him????', see: 'snake' },
  { word: 'NOTEBOOK', hint: 'Where I was born. Lined paper, wire binding.', see: 'about' },
  { word: 'CHANNEL', hint: 'Trusty TV is on ___ 21. Turn the knob for more.', see: 'tv' },
  { word: 'OATS', hint: 'Horse cereal. No milk.' },
  { word: 'BLACKJACK', hint: 'The card game I deal at the horse casino.', see: 'casino' },
  { word: 'FLINT', hint: '___ Nogood rides in Da Tractor Crew.', see: 'comics' },
  { word: 'SUNSCREEN', hint: 'UV’s way up there today. Wear some.', see: 'weather' },
  { word: 'PONY', hint: 'A small horse. Call me that and see what happens.' },
  { word: 'MATH', hint: 'The class I was born in. 8th grade.', see: 'about' },
  { word: 'SCRIBBLE', hint: 'Too much ink! Draw each line once instead of doing this.', see: 'draw' },
  { word: 'CRIMES', hint: 'Commit ___ for Trusty! (In Grand Theft Trusty, I mean.)', see: 'gta' },
  { word: 'STEED', hint: 'A noble horse. That’s me. Deal with it.' },
  { word: 'GEMINI', hint: 'The AI brain inside TrustyGPT.', see: 'gpt' },
  { word: 'PIPES', hint: 'What I fly through in Flappy Trusty. Deadly.', see: 'flappy' },
  { word: 'FOAL', hint: 'A baby horse. I was one once, on page one.' },
  { word: 'JACKET', hint: 'Only 50 degrees today? That’s ___ weather.', see: 'weather' },
  { word: 'NOGOOD', hint: 'Flint’s last name. It suits him.', see: 'comics' },
  { word: 'CARTOON', hint: 'A drawn character, like me. Way better than a real horse.' },
  { word: 'TRUSTY', hint: 'It’s me. Who else would it be?', see: 'about' },
  { word: 'BOUNTY', hint: 'The ___ Hunter, now airing on Trusty TV.', see: 'tv' },
  { word: 'LASSO', hint: 'A cowboy’s rope. Try it on me. I dare you.' },
  { word: 'INSURANCE', hint: 'What I offer when I’m showing an Ace.', see: 'casino' },
  { word: 'STICK', hint: 'I’m a ___ figure horse, and proud of it.' },
  { word: 'DRIZZLE', hint: 'Light rain. Annoying, like a fly on my back.', see: 'weather' },
  { word: 'HOMEWORK', hint: 'What should’ve been on that notebook paper instead of me.' },
  { word: 'SPONGEBOB', hint: 'He’s on channel 23. Lives in a pineapple.', see: 'spongebob' },
  { word: 'KICK', hint: 'Drink water on hot days, or I’ll ___ you.', see: 'weather' },
  { word: 'SMITH', hint: 'Jim ___, of Da Tractor Crew.', see: 'comics' },
  { word: 'MEMORIZE', hint: 'Draw Trusty gives you two seconds to do this to me.', see: 'draw' },
  { word: 'UNICORN', hint: 'A horse with a horn. Show-off.' },
  { word: 'RIGGED', hint: 'Every game in my game corner is probably ___.', see: 'games' },
  { word: 'BACK', hint: 'Mine is one long, straight line. Longest in the business.', see: 'draw' },
  { word: 'FORECAST', hint: 'What Weatherman Trusty delivers every day.', see: 'weather' },
  { word: 'CRAYON', hint: 'A wax drawing stick. I’m too classy to be drawn in one.' },
  { word: 'HORSE', hint: 'What I am. Stick figure, but still.' },
  { word: 'ARCADE', hint: 'The part of my game corner hosted by other sites.', see: 'games' },
  { word: 'TROJAN', hint: 'The ___ Horse: a wooden horse full of soldiers. Sneaky. I like it.' },
  { word: 'DETENTION', hint: 'Where you end up for drawing horses in math class.' },
  { word: 'JULIET', hint: 'Romeo and ___, the love story on Trusty TV.', see: 'tv' },
  { word: 'APPLE', hint: 'Red, crunchy, keeps the vet away.' },
  { word: 'HORSEGUN', hint: 'Lin ___ of Da Tractor Crew. Great last name.', see: 'comics' },
  { word: 'CANTER', hint: 'Faster than a trot, slower than a gallop.' },
  { word: 'RADAR', hint: 'My weather ___ is on the fritz. Try again later.', see: 'weather' },
  { word: 'DEALER', hint: 'My job at the horse casino. I always win.', see: 'casino' },
  { word: 'GRAPHITE', hint: 'What pencil lead is really made of. Basically my blood.' },
  { word: 'BOWL', hint: 'Lead your team to the Trusty ___!', see: 'football' },
  { word: 'MINION', hint: 'What you’ll be once I take over the world.' },
  { word: 'SHADING', hint: 'Overcast skies look like pencil ___ up there.', see: 'weather' },
  { word: 'COWBOY', hint: 'A guy in a big hat who thinks he can ride me.' },
  { word: 'STATIC', hint: 'What you see between channels on Trusty TV.', see: 'tv' },
  { word: 'EIGHTH', hint: 'The grade I was drawn in.', see: 'about' },
  { word: 'HOBBY', hint: 'A ___ horse is a stick with a horse head on it. My cousin.' },
  { word: 'BUST', hint: 'Go over 21 at the horse casino and you ___.', see: 'casino' },
  { word: 'SEASON', hint: 'Da Tractor Crew has four of these. One went missing.', see: 'comics' },
  { word: 'THUNDER', hint: 'Storms rolling in. Loud, but I’m louder.', see: 'weather' },
  { word: 'MANE', hint: 'Real horses have long hair here. I’m a stick figure, so no.' },
  { word: 'POLYGON', hint: '3D Trusty is built out of hundreds of these.', see: 'viewer' },
  { word: 'HELPFUL', hint: 'What TrustyGPT is. Mostly.', see: 'gpt' },
  { word: 'CATTLE', hint: 'Trusty’s Crazy ___ 3D. Fight to the death.', see: 'cattle' },
  { word: 'SPIRAL', hint: 'The wire coil holding my notebook together.' },
  { word: 'ZEBRA', hint: 'A horse in a referee shirt.' },
  { word: 'WORLD', hint: '___ domination. Step one: this website.', see: 'about' },
  { word: 'RECESS', hint: 'My favorite class. Wait, that’s not a class?' },
  { word: 'TASTY', hint: 'How to Make Yourself ___, now airing on Trusty TV.', see: 'tv' },
  { word: 'HOOVES', hint: 'What I’ve got instead of feet.' },
  { word: 'BAILOUT', hint: 'Go broke at blackjack and I’ll spot you $100. Don’t tell anyone.', see: 'casino' },
  { word: 'SKETCH', hint: 'A quick drawing. I started out as one.' },
  { word: 'FARM', hint: 'Where tractors live. Most horses too, honestly.' },
  { word: 'CLOUDY', hint: 'Gray skies. The sun called in sick.', see: 'weather' },
  { word: 'TRUSTLE', hint: 'This game. You’re playing it right now.' },
  { word: 'JOCKEY', hint: 'The little guy who rides racehorses. Not on my back.' },
  { word: 'EPISODE', hint: 'Season 1 of Da Tractor Crew has five of these.', see: 'comics' },
  { word: 'FOIL', hint: 'First, Outer, Inner, Last. The ___ Way is on Trusty TV.', see: 'tv' },
  { word: 'HORSESHOE', hint: 'U-shaped, nailed to a hoof, supposedly lucky.' },
  { word: 'VILLAIN', hint: 'Some call me a ___. I prefer “visionary.”' },
  { word: 'TRAFFIC', hint: 'Trusty’s ___ Crime Simulator. Can Trusty drive? (No.)', see: 'driving' },
  { word: 'INK', hint: 'What markers are full of. Don’t use too much.', see: 'draw' },
  { word: 'RODEO', hint: 'Where cowboys try to ride angry horses. I’d win.' },
  { word: 'KNOB', hint: 'Turn it to flip the channel on Trusty TV.', see: 'tv' },
  { word: 'TEACHER', hint: 'Mrs. Cabasa’s job. Sorry about the margins.', see: 'about' },
  { word: 'MULE', hint: 'Half horse, half donkey, all attitude.' },
  { word: 'CONQUER', hint: 'What I plan to do to the world. Soon.' },
  { word: 'FLAP', hint: 'Press Space or tap to ___.', see: 'flappy' },
  { word: 'SUNSET', hint: 'After this, I forecast tomorrow instead.', see: 'weather' },
  { word: 'REINS', hint: 'The straps you’d hold if you rode me. You won’t.' },
  { word: 'PORTRAIT', hint: 'A picture of someone’s face. I’d pose for one.' },
  { word: 'HOLD', hint: 'Press C in Trustis to save a piece for later.', see: 'trustis' },
  { word: 'WAGON', hint: 'Something horses pull. I’m on break.' },
  { word: 'NEWS', hint: 'SNN: the Stallion ___ Network.', see: 'snn' },
  { word: 'CENTAUR', hint: 'Half man, half horse, all trouble.' },
  { word: 'RULER', hint: 'Keeps your lines straight. Also what I’ll be of the world.' },
  { word: 'CHIPS', hint: 'What you bet with at the horse casino.', see: 'casino' },
  { word: 'MISSING', hint: 'Da Tractor Crew Season 2’s status. There’s a reward.', see: 'season2' },
  { word: 'CARROT', hint: 'The only vegetable I trust.' },
  { word: 'GOLDEN', hint: 'Jason and the ___ Belt, now airing on Trusty TV.', see: 'tv' },
  { word: 'NECK', hint: 'Connects my head to my very long back.', see: 'draw' },
  { word: 'HENCHMAN', hint: 'I’m hiring one. Apply within.' },
  { word: 'STABLE', hint: 'Where most horses sleep. I sleep on notebook paper.' },
  { word: 'BATTLE', hint: 'The ___ of Pharsalus, a Trusty TV history lesson.', see: 'tv' },
  { word: 'MARKER', hint: 'Pencil and ___: what I’m drawn in.', see: 'about' },
  { word: 'BUCK', hint: 'What I do when someone tries to ride me.' },
  { word: 'GEOMETRY', hint: 'My head’s a circle and my back’s a line. I’m basically this subject.' },
  { word: 'CLICKS', hint: 'Every tap on my face up in the header counts as one.', see: 'leaderboard' },
  { word: 'SNOW', hint: 'Build a ___ horse. It better look like me.', see: 'weather' },
  { word: 'CREW', hint: 'Da Tractor ___.', see: 'comics' },
  { word: 'MUSTANG', hint: 'A wild horse. Also a car I’m not allowed to drive.' },
  { word: 'EMPIRE', hint: 'What I’m building. You’ll see.' },
  { word: 'PAPER', hint: 'Home sweet home. Lined, please.' },
  { word: 'ARENA', hint: 'Where the Crazy Cattle fight to the death.', see: 'cattle' },
  { word: 'COLT', hint: 'A young boy horse.' },
  { word: 'TRAILER', hint: 'The 30,000 Bits ___, now airing on Trusty TV.', see: 'tv' },
  { word: 'PASTURE', hint: 'A big grassy field where horses graze.' },
  { word: 'SCHEME', hint: 'What I’m always doing behind this smile.' },
  { word: 'DRAW', hint: '___ Trusty: how well do you know me?', see: 'draw' },
  { word: 'LOCKER', hint: 'Where the notebook with me in it spent its nights.' },
  { word: 'BRONCO', hint: 'A wild, bucking horse. Also a football team.' },
  { word: 'PERFECT', hint: 'A ___ Clear in Trustis empties the whole board.', see: 'trustis' },
  { word: 'SUGAR', hint: 'Hand me a ___ cube and I might spare you.' },
  { word: 'PODIUM', hint: 'The top three on my leaderboards stand on it.', see: 'leaderboard' },
  { word: 'SHARPEN', hint: 'What you do to a pencil before drawing me.' },
  { word: 'OUTLAW', hint: 'What the sheriff calls me.' },
  { word: 'DERBY', hint: 'The Kentucky ___. I’d win it with my eyes closed.' },
  { word: 'ANTENNA', hint: 'The rabbit ears on top of Trusty TV.', see: 'tv' },
  { word: 'LEGS', hint: 'Four of them, in two pairs.', see: 'draw' },
  { word: 'CHAOS', hint: 'My favorite thing to cause.' },
  { word: 'SALOON', hint: 'A cowboy bar with swinging doors.' },
  { word: 'WHISKEY', hint: 'The Last Bit of ___, now airing on Trusty TV.', see: 'tv' },
  { word: 'SHERIFF', hint: 'The law in cowboy towns. We don’t get along.' },
  { word: 'EQUATION', hint: 'Math with an equals sign in it. I solved zero of them.' },
  { word: 'PEGASUS', hint: 'A horse with wings. Flappy Trusty is basically this.', see: 'flappy' },
  { word: 'FENCE', hint: 'What keeps horses in. Doesn’t work on me.' },
  { word: 'GLUE', hint: 'Don’t ask what it used to be made from. Seriously.' },
  { word: 'SUNNY', hint: 'Not a cloud in the sky. Even I look good in this light.', see: 'weather' },
  { word: 'MARE', hint: 'A grown-up girl horse.' },
  { word: 'OVERLORD', hint: 'My future job title. Practice saying it.' },
  { word: 'BURGER', hint: 'A Big Mac is one. My unhealthy snack in Trusty Snake.', see: 'snake' },
  { word: 'CAROUSEL', hint: 'A ride full of horses that can’t run away. Tragic.' },
  { word: 'CAMPAIGN', hint: 'The Joe Mama ___ Ad, now airing on Trusty TV.', see: 'tv' },
  { word: 'TROT', hint: 'A horse’s jog.' },
  { word: 'WESTERN', hint: 'A cowboy movie. My kind of genre.' },
  { word: 'DESK', hint: 'I was drawn in a notebook, on top of one of these, during math.' },
  { word: 'BLOCKS', hint: 'What you stack in Trustis.', see: 'trustis' },
  { word: 'KNIGHT', hint: 'The chess piece shaped like a horse.' },
  { word: 'MAYHEM', hint: 'Chaos’s cousin. Also my middle name.' },
  { word: 'HARVEST', hint: 'Busy season for tractors.' },
  { word: 'SNORT', hint: 'A horse’s way of saying “whatever.”' },
  { word: 'MARATHON', hint: 'Channel 23 plays a SpongeBob Season 2 ___.', see: 'spongebob' },
  { word: 'FILLY', hint: 'A young girl horse.' },
  { word: 'CRIMINAL', hint: 'TrustyGPT is here to assist in ___ activity.', see: 'gpt' },
  { word: 'STIRRUP', hint: 'Where your feet go when you ride a horse. Not this one.' },
  { word: 'LINES', hint: 'Stay on my ___! That’s how Draw Trusty scores you.', see: 'draw' },
  { word: 'CHARIOT', hint: 'An ancient racing cart pulled by horses.' },
  { word: 'PLOW', hint: 'What a tractor pulls. What I’ll do through my enemies.' },
  { word: 'JOKE', hint: 'Ask TrustyGPT to tell you a horse ___.', see: 'gpt' },
  { word: 'RANCH', hint: 'A farm for horses and cows. Also a salad dressing.' },
  { word: 'SPIN', hint: 'Drag 3D Trusty to ___ him around.', see: 'viewer' },
  { word: 'FIGURE', hint: 'Stick ___. That’s me, head to legs.' },
  { word: 'HAYSTACK', hint: 'Where you’d look for a needle. Or take a nap.' },
  { word: 'BOOM', hint: 'Every flap in Flappy Trusty goes vine ___.', see: 'flappy' },
  { word: 'GROOM', hint: 'Brush a horse. Also the guy at a wedding.' },
  { word: 'PADDOCK', hint: 'A small fenced field for horses.' },
  { word: 'FORTNITE', hint: 'Trusty Plays ___, now airing on Trusty TV.', see: 'tv' },
  { word: 'PANEL', hint: 'One box on a comic page.', see: 'comics' },
  { word: 'SHOE', hint: 'Horses wear them nailed on. Ouch.' },
  { word: 'TROUGH', hint: 'A long box of water that horses drink from.' },
  { word: 'FRACTION', hint: 'Half a horse is one of these.' },
  { word: 'HOWDY', hint: 'How cowboys say hi. I say whaddup.' },
  { word: 'PALOMINO', hint: 'A golden horse with a white mane. Fancy.' },
  { word: 'BRIDLE', hint: 'Headgear for steering a horse. Nobody steers me.' },
  { word: 'LIVE', hint: 'Trusty TV is always ___. Tune in.', see: 'tv' },
  { word: 'BLINDERS', hint: 'Eye flaps so a horse only looks straight ahead.' },
  { word: 'DIESEL', hint: 'What a tractor drinks.' },
  { word: 'RIBBON', hint: 'A blue one means first place at the horse show.' },
  { word: 'ROCKING', hint: 'A ___ horse goes back and forth and never gets anywhere.' },
  { word: 'WANTED', hint: 'What my poster says. Dead or alive.' },
  { word: 'TAIL', hint: 'It’s so foggy I can’t even see my own ___.', see: 'weather' },
  { word: 'BUGGY', hint: 'A horse and ___.' },
  { word: 'FIELD', hint: 'Where tractors plow.' },
  { word: 'RACEHORSE', hint: 'What I’d be if I could focus.' },
  { word: 'SCHOOL', hint: 'Middle ___, 8th grade math: where it all started.', see: 'about' },
  { word: 'SPURS', hint: 'Poke me with these and you’ll regret it.' },
  { word: 'DONKEY', hint: 'My cousin with the big ears. We don’t talk.' },
  { word: 'NIGHTMARE', hint: 'A bad dream. Also, technically, a horse at night.' },
  { word: 'CARRIAGE', hint: 'Something horses pull. Cinderella rode in one.' },
  { word: 'HORSEPLAY', hint: 'What I call my crimes.' },
  { word: 'STAMPEDE', hint: 'A whole herd running at once. Get out of the way.' },
  { word: 'PONYTAIL', hint: 'A hairstyle named after my kind.' },
  { word: 'BACKPACK', hint: 'What carried the notebook I live in.' },
  { word: 'MEADOW', hint: 'A grassy field. Great for galloping.' },
  { word: 'CLOP', hint: 'The sound of hooves on a road.' },
  { word: 'ARTIST', hint: 'Whoever drew me. A genius, obviously.' },
  { word: 'FARRIER', hint: 'The person who nails shoes onto horses.' },
  { word: 'BELL', hint: 'Rings when class is over. Saved by it.' },
  { word: 'HORSEFLY', hint: 'A big biting bug. No relation.' },
  { word: 'CROPS', hint: 'What farmers grow. Tractors help.' },
  { word: 'DRAWING', hint: 'What I am, technically. Pencil on paper.' },
  { word: 'GRAPH', hint: 'Trustis is played on ___ paper.', see: 'trustis' },
  { word: 'STUDENT', hint: 'What my creator was supposed to be in math class.' },
  { word: 'SMUDGE', hint: 'What happens when you rub a pencil drawing. Don’t.' },
  { word: 'QUIZ', hint: 'Pop ___: the perfect time to doodle a horse.' },
  { word: 'RIDER', hint: 'Nobody gets to be mine. Nobody.' },
];
